<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /var/www/sites/default/files/civicrm/ext/be.cncd.civienketo/xml/schema/CRM/Civienketo/EnketoForm.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:24973328f71a2f0cf486b82f8761051f)
 */

/**
 * Database access object for the EnketoForm entity.
 */
class CRM_Civienketo_DAO_EnketoForm extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_enketo_form';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique EnketoForm ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * ID of the remote form
   *
   * @var int unsigned
   */
  public $form_id;

  /**
   * Name of the form.
   *
   * @var string
   */
  public $title;

  /**
   * API URL
   *
   * @var string
   */
  public $url;

  /**
   * URL for downloading data.
   *
   * @var string
   */
  public $data_url;

  /**
   * URL of enketo web form
   *
   * @var string
   */
  public $enketo_url;

  /**
   * Number of records
   *
   * @var int unsigned
   */
  public $num_of_submissions;

  /**
   * Date of the last record submission
   *
   * @var string
   */
  public $last_submission_time;

  /**
   * Date of the last imporation
   *
   * @var string
   */
  public $last_importation_time;

  /**
   * If true - the form is active.
   *
   * @var boolean
   */
  public $downloadable;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_enketo_form';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique EnketoForm ID',
          'required' => TRUE,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'form_id' => [
          'name' => 'form_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Form ID'),
          'description' => 'ID of the remote form',
          'required' => TRUE,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Title'),
          'description' => 'Name of the form.',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'url' => [
          'name' => 'url',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('URL'),
          'description' => 'API URL',
          'maxlength' => 256,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'data_url' => [
          'name' => 'data_url',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Data URL'),
          'description' => 'URL for downloading data.',
          'maxlength' => 256,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'enketo_url' => [
          'name' => 'enketo_url',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Enkto form URL'),
          'description' => 'URL of enketo web form',
          'maxlength' => 256,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'num_of_submissions' => [
          'name' => 'num_of_submissions',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of submissions'),
          'description' => 'Number of records',
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'last_submission_time' => [
          'name' => 'last_submission_time',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Last submission timestamp'),
          'description' => 'Date of the last record submission',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'last_importation_time' => [
          'name' => 'last_importation_time',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Last importation timestamp'),
          'description' => 'Date of the last imporation',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
        'downloadable' => [
          'name' => 'downloadable',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Downloadable'),
          'description' => 'If true - the form is active.',
          'table_name' => 'civicrm_enketo_form',
          'entity' => 'EnketoForm',
          'bao' => 'CRM_Civienketo_DAO_EnketoForm',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'enketo_form', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'enketo_form', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
